

services:

  web:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: web

    env_file:
      - .env

    volumes:
      - .:/usr/src/app
      - static_volume:/usr/src/app/staticfiles
      - media_volume:/usr/src/app/media


    depends_on:
      postgres:
        condition: service_healthy

      redis:
        condition: service_started

      minio:
        condition: service_started

    command: >
      sh -c "
      python manage.py migrate &&
      gunicorn config.wsgi:application
      --bind 0.0.0.0:8000
      --workers 4
      --threads 2
      --timeout 120
      "
    expose:
      - "8000"


    networks:
      - frontend
      - backend
      - storage

  postgres:

    image: postgres:15

    restart: unless-stopped

    env_file:
      - .env

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"
        ]
      interval: 10s
      timeout: 5s
      retries: 5

    networks:
      - backend

  redis:

    image: redis:latest

    restart: unless-stopped

    command: redis-server --appendonly yes

    volumes:
      - redis_data:/data

    networks:
      - backend

  minio:

    image: minio/minio:RELEASE.2025-04-03T14-56-28Z 

    command: server /data --console-address ":9001"

    env_file:
      - .env

    volumes:
      - minio_data:/data

    networks:
      - storage

  celery:

    build: .

    container_name: celery_worker

    command: celery -A config worker -l info

    env_file:
      - .env

    depends_on:
      - redis

    networks:
      - backend
      - storage

  celery-beat:

    build: .

    container_name: celery_beat

    command: celery -A config beat -l info

    env_file:
      - .env

    depends_on:
      - redis

    networks:
      - backend

  nginx:
    image: nginx:latest    
    
    container_name: nginx

    depends_on:
      - web

    ports:
      - "80:80"

    networks:
      - frontend  

    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - static_volume:/usr/src/app/staticfiles:ro
      - media_volume:/usr/src/app/media:ro  

volumes:
  postgres_data:
  redis_data:
  minio_data:
  static_volume:
  media_volume:  




networks:
  frontend:
  backend:
    internal: true
  storage:
    internal: true