apiVersion: v1
kind: Secret
metadata: 
  name: django-secret
  namespace: storage-manager
type: Opaque

stringData: 
  SECRET_KEY: "django-insecure-#kqzh!dwm082k3sukm2*j)t6qtwv6wuay@h@g72%g=nyux%d6+"
  POSTGRES_PASSWORD: "admin"
  MINIO_ACCESS_KEY: "storageadmin" 
  MINIO_SECRET_KEY: "Storage@2026"















